channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - natsort
  - scipy
  - umap-learn
  - scikit-learn
  - seaborn
  - pyranges
  - r-base
  - r-ggplot2
  - r-pheatmap
  - r-ggrepel
  - r-ggpubr
  - r-envstats
  - r-viridislite
  - r-data.table
  - r-patchwork
  - r-gridextra
  - bioconductor-genomicranges
  - bioconductor-biomart
