---
title: "R script for Figure 3"
output: 
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Figure 3
```{r }
library(ggplot2)
library(data.table)
library(gridExtra)
```

### Figure 3A

```{r }
preds <- read.csv(
  "../../data/genomic_sequences/spliceai_donor_greater_3.csv", row.names = 1)
info <- read.delim("../../data/genomic_sequences/match_3_plus.tsv")
info$id <- paste(info$chrom, info$start, info$end, info$strand, sep = "|")
ok <- match(unique(info$id), info$id)
preds <- data.frame(info[ok, ], preds[ok, ])

tmp_donor_spliceai <- reshape2::melt(
  preds, measure.vars = c("UJ_match_3", "KI_donor"))
tmp_donor_spliceai$variable <- gsub("UJ_match_3", "cryptic", fixed = TRUE,
                                    tmp_donor_spliceai$variable)
tmp_donor_spliceai$variable <- gsub("KI_donor", "canonical", fixed = TRUE,
                                    tmp_donor_spliceai$variable)

preds <- read.csv(
  "../../data/genomic_sequences/spliceai_acceptor_greater_3.csv", row.names = 1)
info <- read.delim("../../data/genomic_sequences/match_5_plus.tsv")
info$id <- paste(info$chrom, info$start, info$end, info$strand, sep = "|")
ok <- match(unique(info$id), info$id)
preds <- data.frame(info[ok, ], preds[ok, ])

tmp_acceptor_spliceai <- reshape2::melt(
  preds, measure.vars = c("UJ_match_5", "KI_acceptor"))
tmp_acceptor_spliceai$variable <- gsub("UJ_match_5", "cryptic", fixed = TRUE,
                                       tmp_acceptor_spliceai$variable)
tmp_acceptor_spliceai$variable <- gsub("KI_acceptor", "canonical", fixed = TRUE,
                                       tmp_acceptor_spliceai$variable)

ki_3ss <- read.delim("../../data/genomic_sequences/3ss_canon_seqs.tsv",
                     row.names = 1)[, 1]

uj_3ss <- read.delim("../../data/genomic_sequences/3ss_trt_seqs.tsv",
                     row.names = 1)
uj_3ss <- unlist(uj_3ss[, grep("rand", colnames(uj_3ss))])

ki_5ss <- read.delim("../../data/genomic_sequences/5ss_canon_seqs.tsv",
                     row.names = 1)[, 1]

uj_5ss <- read.delim("../../data/genomic_sequences/5ss_trt_seqs.tsv",
                     row.names = 1)
uj_5ss <- unlist(uj_5ss[, grep("rand", colnames(uj_5ss))])

tmp_3ss <- rbind(data.frame(type = "canonical", score = ki_3ss),
                   data.frame(type = "cryptic", score = uj_3ss))

tmp_5ss <- rbind(data.frame(type = "canonical", score = ki_5ss),
                      data.frame(type = "cryptic", score = uj_5ss))
```

```{r 3_A}
ggplot(tmp_5ss, aes(score, color = type)) +
  labs(title = "5ss",
       x = "MaxEnt score5ss",
       y = "Density") +
  geom_vline(xintercept = mean(tmp_5ss$score[tmp_5ss$type == "cryptic"]),
             linetype = "dashed", color = "red") +
  geom_vline(xintercept = mean(tmp_5ss$score[tmp_5ss$type == "canonical"]),
             linetype = "dashed", color = "black") +
  stat_ecdf() +
  scale_color_manual(values = c("black", "red"), name = "category") +
  theme_classic()
```


### Figure 3 B

```{r 3_B}
ggplot(tmp_3ss, aes(score, color = type)) +
  labs(title = "3ss",
       x = "MaxEnt score3ss",
       y = "Density") +
  geom_vline(xintercept = mean(tmp_3ss$score[tmp_3ss$type == "cryptic"]),
             linetype = "dashed", color = "red") +
  geom_vline(xintercept = mean(tmp_3ss$score[tmp_3ss$type == "canonical"]),
             linetype = "dashed", color = "black") +
  stat_ecdf() +
  scale_color_manual(values = c("black", "red"), name = "category") +
  theme_classic()
```

### Figure 3 C

```{r 3_C}

ggplot(tmp_donor_spliceai, aes(value, color = variable)) +
  labs(title = "5ss",
       x = "SpliceAI donor probability",
       y = "Density") +
  geom_vline(
    xintercept = mean(
      tmp_donor_spliceai$value[tmp_donor_spliceai$variable == "cryptic"]),
             linetype = "dashed", color = "red") +
  geom_vline(
    xintercept = mean(
      tmp_donor_spliceai$value[tmp_donor_spliceai$variable == "canonical"]),
             linetype = "dashed", color = "black") +
  stat_ecdf() +
  scale_color_manual(values = c("black", "red"), name = "category") +
  theme_classic()
```

### Figure 3 D

```{r 3_D}
ggplot(tmp_acceptor_spliceai, aes(value, color = variable)) +
  labs(title = "3ss",
       x = "SpliceAI acceptor probability",
       y = "Density") +
  geom_vline(
    xintercept = mean(
      tmp_acceptor_spliceai$value[tmp_acceptor_spliceai$variable == "cryptic"]),
             linetype = "dashed", color = "red") +
  geom_vline(xintercept = mean(
    tmp_acceptor_spliceai$value[tmp_acceptor_spliceai$variable == "canonical"]),
             linetype = "dashed", color = "black") +
  stat_ecdf() +
  scale_color_manual(values = c("black", "red"), name = "category") +
  theme_classic()
```

### Figure 3 E

```{r 3_E}
# spliceAI predictions from code/figure_3/Run_spliceAI_on_junctions.ipynb

ujs <- read.csv(
  "../../data/dtag_experiments/random_500_ujs.csv"
)

# Calculate MaxEntScores ####
ujs <- ujs[ujs$strand == "+", ]

maxents <- do.call(rbind, lapply(1:nrow(ujs), function(x) {
  seq <- as.character(getSeq(
    Hsapiens,
    ujs$chr[x],
    ujs$end[x] - 19,
    ujs$end[x] + 3
  ))

  score_3 <- calculateMaxEntScanScore(seq, 3)

  seq <- as.character(getSeq(
    Hsapiens,
    ujs$chr[x],
    ujs$start[x] - 3,
    ujs$start[x] + 5
  ))

  score_5 <- calculateMaxEntScanScore(seq, 5)

  c(
    as.numeric(score_3),
    as.numeric(score_5)
  )
}))
colnames(maxents) <- c("score_3", "score_5")

# Load SpliceAI predictions ####
files <- c(
  "../../data/dtag_experiments/acceptor_spliceai_start.txt",
  "../../data/dtag_experiments/donor_spliceai_start.txt",
  "../../data/dtag_experiments/acceptor_spliceai_end.txt",
  "../../data/dtag_experiments/donor_spliceai_end.txt"
)

dat <- lapply(files, read.table)

preds <- cbind(
  do.call(cbind, lapply(dat[1:2], function(x) x[, 99])),
  do.call(cbind, lapply(dat[3:4], function(x) x[, 101]))
)
colnames(preds) <- c(
  "acc_start",
  "don_start",
  "acc_end",
  "don_end"
)

merged <- data.frame(
  ujs,
  maxents,
  preds
)

p <- ggplot(
  merged,
  aes(score_3, acc_end, color = class)
) +
  labs(
    title = "Predicted 3' Splice Site Strength",
    x = "MaxEntScore [3']",
    y = "Splice AI acceptor [3']"
  ) +
  geom_point() +
  scale_color_manual(
    values = c("black", "red"),
    labels = c("canonical", "cryptic")
  ) +
  theme_classic()
p
```

### Figure 3 F

```{r 3_F}
p <- ggplot(
  merged,
  aes(score_5, don_start, color = class)
) +
  geom_point() +
  labs(
    title = "Predicted 5' Splice Site Strength",
    x = "MaxEntScore [5']",
    y = "Splice AI donor [5']"
  ) +
  scale_color_manual(
    values = c("red", "black"),
    labels = c("canonical", "cryptic")
  ) +
  theme_classic()
p
```

### Figure 3 H

```{r figure_3_h, fig.dim = c(6,4), out.height = 6, out.width = 4}
# Load R libs ####
library(pheatmap)

# Load data ####
ki_5ss <- read.csv(
  "../../data/eclip_overlaps/summary_tables/ki_5ss_summary.csv",
  row.names = 1)
ki_3ss <- read.csv(
  "../../data/eclip_overlaps/summary_tables/ki_3ss_summary.csv",
  row.names = 1)

dhx15_5ss <- read.csv(
  "../../data/eclip_overlaps/summary_tables/cryptic_5ss_summary.csv",
  row.names = 1)
dhx15_3ss <- read.csv(
  "../../data/eclip_overlaps/summary_tables/cryptic_3sss_summary.csv",
  row.names = 1)

# Define column annotation #####
anno_col_3ss <- data.frame(distance = c(rev(seq(1, 250)), seq(1, 75)))
anno_col_5ss <- data.frame(distance = c(rev(seq(1, 75)), seq(1, 250)))

# Define row annotation ####
anno_row <- read.csv(
  "../../data/eclip_overlaps/summary_tables/label_annotation.csv",
  row.names = 1, header = FALSE)


# Create heatmaps ####
pheatmap(ki_5ss,
         cluster_cols = FALSE,
         cluster_rows = FALSE,
         gaps_col = 75,
         breaks = seq(-3.5, 3.5, length = 101),
         show_rownames = FALSE, show_colnames = FALSE,
         gaps_row = c(9, 15, 26, 42),
         annotation_row = anno_row,
         main = "Canonical 5'ss",
         fontsize_row = 8
)

pheatmap(ki_3ss,
         cluster_cols = FALSE,
         cluster_rows = FALSE,
         gaps_col = 250,
         breaks = seq(-3.5, 3.5, length = 101),
         show_rownames = FALSE, show_colnames = FALSE,
         gaps_row = c(9, 15, 26, 42),
         main = "Canonical 3'ss",
         annotation_row = anno_row,
)

pheatmap(dhx15_5ss,
         cluster_cols = FALSE,
         cluster_rows = FALSE,
         gaps_col = 75,
         breaks = seq(-3.5, 3.5, length = 101),
         show_rownames = FALSE, show_colnames = FALSE,
         gaps_row = c(9, 15, 26, 42),
         main = "Cryptic 5'ss",
         annotation_row = anno_row
)

pheatmap(dhx15_3ss,
         cluster_cols = FALSE,
         cluster_rows = FALSE,
         gaps_col = 250,
         breaks = seq(-3.5, 3.5, length = 101),
         show_rownames = FALSE, show_colnames = FALSE,
         gaps_row = c(9, 15, 26, 42),
         main = "Cryptic 5'ss",
         annotation_row = anno_row
)
```
